### ISSUE TITLE
Issues on upgrading to 1.1.0

### ISSUE THREAD

**Issue by VincentLoy** [hipay/hipay-enterprise-sdk-woocommerce#1]
Hello,

I got some issues while upgrading to v1.1.0. (I'm currently trying to upgrade the plugin on localhost only).

I tried 2 ways of upgrading the plugin : 
- If I keep the 1.0.0 activated, and try to update all plugin's files manually, the server just crash and when I look into apache error.log I get this error : 
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_mysqli.dll' - /usr/lib/php/20151012/php_mysqli.dll: cannot open shared object file: No such file or directory in Unknown on line 0`
So I have DLL files error and I'm on a Linux machine (Debian 9 Stretch). I already checked php.ini configuration file to see if the error was there, but everything looks ok.
- If I first deactivate the plugin, and then, update all plugin's files. I'm redirected to the website homepage everytime I try to activate the plugin and the activation fail.

I'm trying the update on Wordpress 5.0.3 / WooCommerce 3.5.3. The 1.0.0 plugin's version works great.

**Comment by legithubdeaymeric** [comment]
Hello,

Thanks for your feedback.
Indeed there was a problem during the making of the installation zip.

It is the file "index.php" that has been added in the directory "includes/gateways/local" which poses problem.

We use a custom loader that loads the different classes present in this directory, so a redirection is done on the home when this file is require.

We have modified an archive without files, you can either delete manualy this file to activate the module, or download the new archive that we have made available.

Do not hesitate to inform us if there is still a problem !

Aymeric

**Comment by VincentLoy** [comment]
Hello @legithubdeaymeric !

I'll try and let you know. Thanks for your quick reply.

**Comment by VincentLoy** [comment]
I confirm that the this trick works well.
Other question, after plugin update, all payments are refused with [test cards](https://support.hipay.com/hc/fr/articles/213882649-Comment-tester-les-m%C3%A9thodes-de-paiement-) (for sandbox mode).
Transactions can be seen well in the HiPay back-office, but no one of those cards are working. (Was working well yesterday with plugin 1.0.0)

**Comment by legithubdeaymeric** [comment]
If you see the transactions it's not from the module but from the sandbox environment.
Can you tell us if you are still reproducing the problem today?

**Comment by VincentLoy** [comment]
Hello @legithubdeaymeric 

The problem seems to be solved now. Thanks for your help.
