### ISSUE TITLE
Still some Short_open_tag

### ISSUE THREAD

**Issue by khypsos** [hipay/hipay-enterprise-sdk-woocommerce#2]
Hello, 

After a fresh installed I encountered an error "EOF" when trying to access the admin panel of the plugin. 

It concerns 2 files : 

- https://github.com/hipay/hipay-enterprise-sdk-woocommerce/blob/master/src/woocommerce_hipayenterprise/includes/admin/template/admin-mapping-category-settings.php (line 44)

- https://github.com/hipay/hipay-enterprise-sdk-woocommerce/blob/master/src/woocommerce_hipayenterprise/includes/admin/template/admin-mapping-delivery-settings.php (line 63 & 76)

I had to turn on the short_tag option in production and I'm not really sure this is the way to go when it comes to this functionnality in production.

Short tag may be in other file, but as of today I didn't encountered any others errors.

Thanks for your consideration.

**Comment by JBaptisteLvt** [comment]
Hello !
Thank you for this issue, we will add it to the ROADMAP

**Comment by JBaptisteLvt** [comment]
This has been fixed in version 2.1.0
