### ISSUE TITLE
BUGFIX : Parse error: unexpected end of file admin-mapping-category-settings.php and admin-mapping-delivery-settings.php

### ISSUE THREAD

**Issue by TsuLee** [hipay/hipay-enterprise-sdk-woocommerce#3]
Parse error: syntax error, unexpected end of file in :

\woocommerce_hipayenterprise\includes\admin\template\admin-mapping-category-settings.php on line 62
**`line 44 : <? endforeach; ?> change to <?php endforeach; ?>`**

\woocommerce_hipayenterprise\includes\admin\template\admin-mapping-delivery-settings.php on line 94
**`line 63 : <? endforeach; ?> change to <?php endforeach; ?>`
`line 76 : <? endforeach; ?> change to <?php endforeach; ?>`**

Good luck !

**Comment by JBaptisteLvt** [comment]
Hello :)
This is a duplicate of #2 . This will be treated ASAP
